app:
  env: "dev"
  name: "sambaMW"
  version: "0.0.0"
  tmp_directory_path: "./tmp/sambaMW/dirs"
  tmp_file_path: "./tmp/sambaMW/files"

http:
  host: "0.0.0.0"
  port: "8080"

ss:
  host: "samba"
  port: "445"
  user: "user"
  password: "password"
  share_name: "share"
  connection_pool_size: 20

cache:
  host: "redis"
  port: "6379"
  password: ""
  db: 0

cleaner:
  time_offset: 24h

notifier:
  endpoint: "localhost:9090"